/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class com_kaolafm_sdk_player_core_Lame */

#ifndef _Included_com_kaolafm_sdk_player_core_Lame
#define _Included_com_kaolafm_sdk_player_core_Lame
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kaolafm_sdk_player_core_Lame
 * Method:    getLameVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kaolafm_sdk_player_core_Lame_getLameVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
