/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include<lame.h>
#include "com_kaolafm_sdk_player_core_Lame.h"
/* Header for class com_kaolafm_sdk_player_core_Lame */

/* Class:     com_kaolafm_sdk_player_core_Lame
 * Method:    getLameVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kaolafm_sdk_player_core_Lame_getLameVersion(
		JNIEnv * env, jclass obj) {
	return (*env)->NewStringUTF(env, get_lame_version());
}

